# Generated by Django 2.2.7 on 2019-11-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='fechaNacimiento',
            field=models.DateTimeField(),
        ),
    ]
